/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project16;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;
import model.bean.ArduinoBean;
import model.dao.ArduinoDAO;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DatasetUtilities;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.util.Rotation;
import static sun.misc.MessageUtils.where;

/**
 *
 * @author proxc
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    ControlePorta arduino;
    ArduinoDAO dao = new ArduinoDAO();
    ControlePorta arduino1;
    ArduinoTableModel tableModel = new ArduinoTableModel(dao.read());
    List<ModelArduino> listaDataLedVermelho;
    List<ModelArduino> listaDataLedAmarelo;
    List<ModelArduino> listaDataLedVerde;
    static double totalTempoLedVermelho = 0;
    static double totalTempoLedVerde = 0;
    static double totalTempoLedAmarelo = 0;
    

    public Home() {
        initComponents();
        pnl_detalhes.setVisible(false);
        home.setVisible(true);
        panel_relatorio.setVisible(false);
        pnl_conexao.setVisible(false);
        pnl_chart.setVisible(true);        
        jTable1.setModel(tableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        pnl_home = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnl_sidebar = new javax.swing.JPanel();
        btn_conectar = new javax.swing.JLabel();
        btn_home = new javax.swing.JLabel();
        btn_monitorar_consumo = new javax.swing.JLabel();
        btn_resto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnl_chart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StatusConexao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel_relatorio = new javax.swing.JPanel();
        pnl_conexao = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBLedOn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Jbl_FeebackCon = new javax.swing.JLabel();
        JBLedOff = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_detalhes = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jbl_LedVermelho = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jbl_LedVerde = new javax.swing.JLabel();
        jbl_LedAmarelo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setLayout(new javax.swing.BoxLayout(home, javax.swing.BoxLayout.LINE_AXIS));

        pnl_home.setMaximumSize(new java.awt.Dimension(32760, 32767));
        pnl_home.setPreferredSize(new java.awt.Dimension(784, 39));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bem vindo ao Controlador da sua casa");
        jLabel8.setPreferredSize(new java.awt.Dimension(180, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Para acessar os recursos clique em uma das opções ao lado");
        jLabel12.setPreferredSize(new java.awt.Dimension(180, 40));

        javax.swing.GroupLayout pnl_homeLayout = new javax.swing.GroupLayout(pnl_home);
        pnl_home.setLayout(pnl_homeLayout);
        pnl_homeLayout.setHorizontalGroup(
            pnl_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_homeLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(pnl_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_homeLayout.createSequentialGroup()
                    .addGap(222, 222, 222)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );
        pnl_homeLayout.setVerticalGroup(
            pnl_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_homeLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(pnl_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_homeLayout.createSequentialGroup()
                    .addGap(201, 201, 201)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        home.add(pnl_home);

        pnl_sidebar.setBackground(new java.awt.Color(34, 41, 50));
        pnl_sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_sidebarMouseDragged(evt);
            }
        });
        pnl_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_sidebarMousePressed(evt);
            }
        });

        btn_conectar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_conectar.setForeground(new java.awt.Color(166, 166, 166));
        btn_conectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project16/Icons/plus_18px_1.png"))); // NOI18N
        btn_conectar.setText("Conectar Dispositivo");
        btn_conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_conectarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_conectarMousePressed(evt);
            }
        });

        btn_home.setBackground(new java.awt.Color(48, 201, 235));
        btn_home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_home.setForeground(new java.awt.Color(48, 201, 235));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project16/Icons/home_18px.png"))); // NOI18N
        btn_home.setText("Inicio");
        btn_home.setToolTipText("");
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });

        btn_monitorar_consumo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_monitorar_consumo.setForeground(new java.awt.Color(166, 166, 166));
        btn_monitorar_consumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project16/Icons/clock_18px.png"))); // NOI18N
        btn_monitorar_consumo.setText("Monitorar Consumo");
        btn_monitorar_consumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_monitorar_consumoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_monitorar_consumoMousePressed(evt);
            }
        });

        btn_resto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_resto.setForeground(new java.awt.Color(166, 166, 166));
        btn_resto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project16/Icons/search_18px_2.png"))); // NOI18N
        btn_resto.setText("Detalhes Consumo");
        btn_resto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_restoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_restoMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(22, 27, 33));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("São Judas 2018");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project16/Nova Pasta/if__house_snowglobe_1679641 (1).png"))); // NOI18N

        javax.swing.GroupLayout pnl_sidebarLayout = new javax.swing.GroupLayout(pnl_sidebar);
        pnl_sidebar.setLayout(pnl_sidebarLayout);
        pnl_sidebarLayout.setHorizontalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_sidebarLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_monitorar_consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_resto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        pnl_sidebarLayout.setVerticalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_monitorar_consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_resto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_chart.setBackground(new java.awt.Color(54, 63, 73));
        pnl_chart.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_chartMouseDragged(evt);
            }
        });
        pnl_chart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_chartMousePressed(evt);
            }
        });
        pnl_chart.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(34, 41, 50));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("X  ");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        pnl_chart.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        StatusConexao.setForeground(new java.awt.Color(255, 0, 51));
        StatusConexao.setText("Desconectado");
        pnl_chart.add(StatusConexao, java.awt.BorderLayout.CENTER);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_chart.add(jButton1, java.awt.BorderLayout.LINE_END);

        panel_relatorio.setBackground(new java.awt.Color(255, 255, 255));
        panel_relatorio.setEnabled(false);
        panel_relatorio.setLayout(new javax.swing.BoxLayout(panel_relatorio, javax.swing.BoxLayout.LINE_AXIS));

        pnl_conexao.setBackground(new java.awt.Color(255, 255, 255));
        pnl_conexao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_conexao.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Deseja Se conectar ao Arduino ?");
        jLabel4.setPreferredSize(new java.awt.Dimension(180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Clique no botao para se conectar:");

        jBLedOn.setBackground(new java.awt.Color(153, 255, 153));
        jBLedOn.setText("Conectar");
        jBLedOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLedOnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Status:");

        Jbl_FeebackCon.setText("Não Conectado");

        JBLedOff.setText("Desconectar");
        JBLedOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLedOffActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Conexão com o Arduino");

        javax.swing.GroupLayout pnl_conexaoLayout = new javax.swing.GroupLayout(pnl_conexao);
        pnl_conexao.setLayout(pnl_conexaoLayout);
        pnl_conexaoLayout.setHorizontalGroup(
            pnl_conexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_conexaoLayout.createSequentialGroup()
                .addGroup(pnl_conexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_conexaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(pnl_conexaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_conexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_conexaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(76, 76, 76))
                    .addGroup(pnl_conexaoLayout.createSequentialGroup()
                        .addGroup(pnl_conexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(pnl_conexaoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(Jbl_FeebackCon)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnl_conexaoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jBLedOn)
                .addGap(40, 40, 40)
                .addComponent(JBLedOff)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_conexaoLayout.setVerticalGroup(
            pnl_conexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_conexaoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(pnl_conexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Jbl_FeebackCon))
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addGroup(pnl_conexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLedOn)
                    .addComponent(JBLedOff))
                .addGap(70, 70, 70)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );

        pnl_detalhes.setBackground(new java.awt.Color(255, 255, 255));
        pnl_detalhes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_detalhes.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Total consumido Arduino:");
        jLabel14.setPreferredSize(new java.awt.Dimension(180, 40));

        jLabel16.setText("Led Vermelho Tempo Total Consumido(seg):");

        jbl_LedVermelho.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Mais Detalhes Aplicação");

        jLabel18.setText("Led Verde Tempo Total Consumido (seg):");

        jLabel19.setText("Led Amarelo Tempo Total Consumido (seg):");

        jbl_LedVerde.setText("0");

        jbl_LedAmarelo.setText("0");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        jScrollPane1.setOpaque(false);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "LED", "TEMPO (ms)", "DATA"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(62, 226, 141));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Coloque a data em que deseja verficar o tempo:");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jButton3.setText("Carregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel10.setText("Até");

        javax.swing.GroupLayout pnl_detalhesLayout = new javax.swing.GroupLayout(pnl_detalhes);
        pnl_detalhes.setLayout(pnl_detalhesLayout);
        pnl_detalhesLayout.setHorizontalGroup(
            pnl_detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detalhesLayout.createSequentialGroup()
                .addGroup(pnl_detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_detalhesLayout.createSequentialGroup()
                        .addGroup(pnl_detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_detalhesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl_detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19)
                                    .addGroup(pnl_detalhesLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel18))
                                    .addComponent(jbl_LedAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbl_LedVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbl_LedVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl_detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 462, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnl_detalhesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_detalhesLayout.createSequentialGroup()
                    .addContainerGap(271, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnl_detalhesLayout.setVerticalGroup(
            pnl_detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detalhesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel17)
                .addGap(16, 16, 16)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_LedVermelho)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_LedVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbl_LedAmarelo)
                .addGap(65, 65, 65))
            .addGroup(pnl_detalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_detalhesLayout.createSequentialGroup()
                    .addContainerGap(107, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_chart, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addComponent(pnl_conexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 236, Short.MAX_VALUE)
                    .addComponent(panel_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 234, Short.MAX_VALUE)
                    .addComponent(pnl_detalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_conexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(185, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 62, Short.MAX_VALUE)
                    .addComponent(panel_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 66, Short.MAX_VALUE)
                    .addComponent(pnl_detalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx;
    int xy;
    private void pnl_chartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_chartMousePressed
        // TODO add your handling code here:
        System.out.print("clicaram no grafico");

    }//GEN-LAST:event_pnl_chartMousePressed

    private void pnl_chartMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_chartMouseDragged
        // TODO add your handling code here:


    }//GEN-LAST:event_pnl_chartMouseDragged

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        setLblColor(btn_home);
        resetLblColor(btn_monitorar_consumo);
        resetLblColor(btn_resto);
        resetLblColor(btn_conectar);
        //mostra os paineis de novo
        pnl_chart.setVisible(true);
        pnl_conexao.setVisible(false);
    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_monitorar_consumoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_monitorar_consumoMousePressed
        // TODO add your handling code here:
        setLblColor(btn_monitorar_consumo);
        resetLblColor(btn_home);
        resetLblColor(btn_resto);
        resetLblColor(btn_conectar);
    }//GEN-LAST:event_btn_monitorar_consumoMousePressed

    private void btn_restoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_restoMousePressed
        // TODO add your handling code here:
        setLblColor(btn_resto);
        resetLblColor(btn_monitorar_consumo);
        resetLblColor(btn_home);
        resetLblColor(btn_conectar);

    }//GEN-LAST:event_btn_restoMousePressed

    private void pnl_sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_sidebarMousePressed

    private void pnl_sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnl_sidebarMouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MousePressed

    private void btn_monitorar_consumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_monitorar_consumoMouseClicked
        pnl_chart.setVisible(true);
        pnl_conexao.setVisible(false);
        home.setVisible(false);
        panel_relatorio.setVisible(true);
        pnl_detalhes.setVisible(false);

        PieDataset pizzaDataSet = criarDadosFake();
        //grafico pizza             
        panel_relatorio.removeAll();
        GraficoPizza3D grafico = new GraficoPizza3D(
                "Pessoas por países",
                "Total de Tempo em que cada LED ficou ligado",
                pizzaDataSet
        );

    }

    private JFreeChart createChart(PieDataset pPieDataset, String pTituloGrafico) {

        JFreeChart grafico = ChartFactory.createPieChart3D(
                pTituloGrafico,
                pPieDataset,
                true,
                true,
                false
        );

        PiePlot3D plot = (PiePlot3D) grafico.getPlot();

        plot.setForegroundAlpha(0.7f);

        plot.setStartAngle(0);

        plot.setDirection(Rotation.CLOCKWISE);

//        grafico.pack();
//        grafico.setVisible(true);
        return grafico;
    }//GEN-LAST:event_btn_monitorar_consumoMouseClicked

    private void jBLedOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLedOnActionPerformed
        // conn.comunicacaoArduino(jBLedOn);
        Jbl_FeebackCon.setForeground(Color.green);
        StatusConexao.setForeground(Color.green);
        try {
            arduino1 = new ControlePorta("COM3", 9600);
        } catch (NullPointerException ex) {
            ex.printStackTrace();
        }

        //arduino
        String status = StatusConexao.getText();
        if (status.equals("Desconectado")) {
            //arduino 
            Jbl_FeebackCon.setText("Conectado");
            StatusConexao.setText("Conectado");

//            conn.initialize();
            Thread t = new Thread() {
                public void run() {
                    //the following line will keep this app alive for 1000 seconds,
                    //waiting for events to occur and responding to them (printing incoming messages to console).
                    try {
                        Thread.sleep(1000000);
                    } catch (InterruptedException ie) {
                    }
                }
            };
            t.start();
            System.out.println("Started");
    }//GEN-LAST:event_jBLedOnActionPerformed
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_restoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_restoMouseClicked

        pnl_chart.setVisible(true);
        pnl_conexao.setVisible(false);
        home.setVisible(false);
        panel_relatorio.setVisible(false);
        pnl_detalhes.setVisible(true);
    }//GEN-LAST:event_btn_restoMouseClicked

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        home.setVisible(true);
        pnl_sidebar.setVisible(true);
        pnl_chart.setVisible(true);
        panel_relatorio.setVisible(false);
        pnl_detalhes.setVisible(false);

    }//GEN-LAST:event_btn_homeMouseClicked

    private void JBLedOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLedOffActionPerformed
        // conn.comunicacaoArduino(JBLedOff);

        Jbl_FeebackCon.setForeground(Color.red);
        Jbl_FeebackCon.setText("Desconected");
        StatusConexao.setText("Desconected");
        StatusConexao.setForeground(Color.red);
        arduino1.close();
    }//GEN-LAST:event_JBLedOffActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double tempoLedVermelho = 0;
        double tempoLedAmarelo = 0;
        double tempoLedVerde = 0;

        listaDataLedVermelho = dao.readLedData("LED VERMELHO");
        listaDataLedAmarelo = dao.readLedData("LED AMARELO");
        listaDataLedVerde = dao.readLedData("LED VERDE");

        for (ModelArduino ma : listaDataLedVermelho) {
            tempoLedVermelho += ma.getLedTempo();
        }
        for (ModelArduino ma : listaDataLedAmarelo) {
            tempoLedAmarelo += ma.getLedTempo();
        }
        for (ModelArduino ma : listaDataLedVerde) {
            tempoLedVerde += ma.getLedTempo();

        }

        for (int i = 0; i < listaDataLedAmarelo.size(); i++) {
            if (listaDataLedAmarelo.get(i) != null) {
                totalTempoLedAmarelo += listaDataLedAmarelo.get(i).getLedTempo();
            }
        }

        for (int i = 0; i < listaDataLedVerde.size(); i++) {
            if (listaDataLedVerde.get(i) != null) {
                totalTempoLedVerde += listaDataLedVerde.get(i).getLedTempo();
            }

        }
        for (int i = 0; i < listaDataLedVermelho.size(); i++) {
            if (listaDataLedVermelho.get(i) != null) {
                totalTempoLedVermelho += listaDataLedVermelho.get(i).getLedTempo();
            }
        }

        jbl_LedVermelho.setText("" + tempoLedVermelho);
        jbl_LedVerde.setText("" + tempoLedVerde);
        jbl_LedAmarelo.setText("" + tempoLedAmarelo);
       


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_conectarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_conectarMousePressed
        // TODO add your handling code here:
        setLblColor(btn_conectar);
        resetLblColor(btn_monitorar_consumo);
        resetLblColor(btn_resto);
        resetLblColor(btn_home);
    }//GEN-LAST:event_btn_conectarMousePressed

    private void btn_conectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_conectarMouseClicked
        pnl_conexao.setVisible(true);
        pnl_chart.setVisible(false);
        pnl_detalhes.setVisible(false);
        jLabel1.setVisible(true);
        pnl_chart.setVisible(true);
    }//GEN-LAST:event_btn_conectarMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String pSql01 = jFormattedTextField1.getText();
        tableModel.clear();
        String pSql02 = jFormattedTextField2.getText();
        List<ModelArduino> listAr = dao.loadFromData(pSql01,pSql02);
        
        for (ModelArduino modelArduino : listAr) {
            tableModel.addRow(modelArduino);
        }
       
        jTable1.repaint();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void setLblColor(JLabel lbl) {
        lbl.setForeground(new Color(48, 201, 235));
    }

    public void resetLblColor(JLabel lbl) {
        lbl.setForeground(new Color(166, 166, 166));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);

            }

        });

    }

    private static PieDataset criarDadosFake() {

        DefaultPieDataset dataSet = new DefaultPieDataset();

        dataSet.setValue(
                "Vermelho", totalTempoLedVermelho);
        dataSet.setValue(
                "Amarelo", totalTempoLedAmarelo);
        dataSet.setValue(
                "Verde", totalTempoLedVerde);
        // dataSet.setValue("Srilanca", 3);

        return dataSet;

    }

    public class GraficoPizza3D {

        public GraficoPizza3D(String applicationTitle, String chartTitle, PieDataset pDataSet) {

            JFreeChart graficoPizza3D = createChart(pDataSet, chartTitle);

            ChartPanel painelParaOGrafico = new ChartPanel(graficoPizza3D);

            panel_relatorio.add(painelParaOGrafico, BorderLayout.AFTER_LAST_LINE);

            panel_relatorio.validate();
        }
    }

    public void readJTable(String data) {

        ArduinoDAO dao = new ArduinoDAO();
        
//        if(data.equals("")){
//         ArduinoTableModel tableModel = new ArduinoTableModel(dao.read());    
//        }else{
//         ArduinoTableModel tableModel = new ArduinoTableModel(dao.load(data));   
//        }
//                
//        jTable1.setModel(tableModel);
//        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        dao.read().forEach((a) -> {
            modelo.addRow(new Object[]{
                a.getNomeLed(),
                a.getLedTempo(),
                a.getDataMarcada()
            });
        });
        tableModel.fireTableDataChanged();
        jTable1.setModel(tableModel);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBLedOff;
    private javax.swing.JLabel Jbl_FeebackCon;
    private javax.swing.JLabel StatusConexao;
    private javax.swing.JLabel btn_conectar;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_monitorar_consumo;
    private javax.swing.JLabel btn_resto;
    private javax.swing.JPanel home;
    private javax.swing.JButton jBLedOn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jbl_LedAmarelo;
    private javax.swing.JLabel jbl_LedVerde;
    private javax.swing.JLabel jbl_LedVermelho;
    private javax.swing.JPanel panel_relatorio;
    private javax.swing.JPanel pnl_chart;
    private javax.swing.JPanel pnl_conexao;
    private javax.swing.JPanel pnl_detalhes;
    private javax.swing.JPanel pnl_home;
    private javax.swing.JPanel pnl_sidebar;
    // End of variables declaration//GEN-END:variables
}
